name: Build and Deploy
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: ''
          destination-github-username: 'eliamarcantognini'
          destination-repository-name: '2muchwaste'
          user-email: ${{ secrets.USER_MAIL }}
          user-name: 'eliamarcantognini'
          target-branch: main
