name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: "production"
          base_href: /2muchwaste/
          deploy_branch: main
          angular_dist_build_folder: dist/frontend # The folder where your project is supposed to be after running ng build by the action.
